filebeat.inputs:
- type: log
  paths:
    - /data/tutorial-dataset.log 

output.logstash:
  hosts: ["logstash:5044"]

setup:kibana:
  host: 'https://kibana:5601'
  username: elastic
  password: password
  ssl.certificate_authorities:
    - /etc/pki/ca/ca.crt

  ## TODO:
  # ssl.certificate: "/etc/pki/client/cert.pem"
  # ssl.key: "/etc/pki/client/cert.key"
  