filebeat.inputs:
- type: filestream
  id: pf-core-logs
  paths:
    - /data/logs/*

output.logstash:
  hosts: ["logstash:5044"]
  ssl.certificate_authorities:
    - /usr/share/filebeat/elasticsearch-certs/ca/ca.crt
  ssl.certificate: "/usr/share/filebeat/filebeat-certs/filebeat.crt"
  ssl.key: "/usr/share/filebeat/filebeat-certs/filebeat.pkcs8.key"
